# Generated by Django 2.2.28 on 2023-06-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mithilesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.BigIntegerField()),
                ('dataModel', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
