# Generated by Django 2.2.28 on 2023-06-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230607_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
